# sources.yaml
# お好みで足してください（重複は自動排除）。
feeds:
  # 公式ブログ・研究
  - https://openai.com/blog/rss.xml
  - https://www.anthropic.com/news/rss.xml
  - https://deepmind.google/atom.xml
  - https://ai.googleblog.com/atom.xml
  - https://engineering.fb.com/feed/
  - https://huggingface.co/blog/feed.xml
  - https://www.nvidia.com/en-us/research/feeds/rss/
  - https://techcommunity.microsoft.com/t5/ai-azure-ai-blog/bg-p/AzureAIBlog/rss-board
  - https://mistral.ai/news/index.xml
  - https://stability.ai/feed
  # メディア（AIカテゴリ）
  - https://www.theverge.com/rss/ai-artificial-intelligence/index.xml
  - https://techcrunch.com/category/artificial-intelligence/feed/
  - https://www.reuters.com/technology/artificial-intelligence/rss
  - https://aws.amazon.com/blogs/machine-learning/feed/
  - https://cloud.google.com/blog/topics/ai-ml/rss/
  - https://blog.langchain.dev/rss/
  - https://blog.llamaindex.ai/feed
  - https://export.arxiv.org/rss/cs.CL
  - https://export.arxiv.org/rss/cs.LG
  - https://export.arxiv.org/rss/stat.ML
  
# X（SNS）— どちらか
# A) 公式API（推奨）：Secrets に X_BEARER_TOKEN がある場合のみ動作
x_accounts:
  - OpenAI
  - anthropic
  - googledeepmind
  - _anthropic
  - OpenAIResearch
  - karpathy
  - nvidiaai
  - microsoft
  - googlecloud
  
# B) 代替RSS（Nitter系）— APIが無い場合はこちら（不安定な時は自動スキップ）
x_rss_base: https://nitter.net
x_rss_accounts:
  - OpenAI
  - anthropic
  - googledeepmind
  - karpathy